can_motors:
  - can_id: 1
    can_bus: 0
    name: "test_motor"
    type: "M3508"
    need_calibration: false
#   - can_id: 2
#     can_bus: 0
#     name: "other_motor"
#     type: "M6020"
#     need_calibration: false
# can_imus:
#   - can_bus: 1
#     name: "gimbal_imu"
#     bias: [ 1., 1. ,1. ]
#   - can_bus: 0
#     name: "base_imu"
# gpios:
#   - name: "output"
#     pin: 0
#     mode: 1
#   - name: "input"
#     pin: 1
#     mode: 0
